### ISSUE TITLE
Add XRDP support

### ISSUE THREAD

**Issue by ignisc4t** [akuhnet/hero-vps-lifetime#2]
if this is possible, just add it bro. more useful if we can access it through RD Client. love your youtube channel.

**Comment by vital987** [comment]
First of all it's my project, this guy cloned it, second thing, using XRDP was not working with it due to it's configurations, I didn't got proper colours and sometime it stuck after logging in, so switched to the best option possible, if you like it, please star my repo [here](https://github.com/vital987/vubuntu). I would've praised this guy if he gave me credits by forking it, but he didn't do so after requesting also. Also if you have any issues, checkout the [original repo](https://github.com/vital987/vubuntu), you'll get nothing here.

**Comment by vital987** [comment]
ALSO DEPLOYING THE PROJECT WILL LEAD TO BAN ON RAILWAY(SEE THEIR POLICY), I'VE GOT THE ISSUE PINNED.

**Comment by ignisc4t** [comment]
> First of all it's my project, this guy cloned it, second thing, using XRDP was not working with it due to it's configurations, I didn't got proper colours and sometime it stuck after logging in, so switched to the best option possible, if you like it, please star my repo [here](https://github.com/vital987/vubuntu). I would've praised this guy if he gave me credits by forking it, but he didn't do so after requesting also. Also if you have any issues, checkout the [original repo](https://github.com/vital987/vubuntu), you'll get nothing here.

ah, finally I can get the clear explanation. will send you the star there, love your work.
